local CATS        = STRINGS.SCRAPBOOK.CATS
local SUBCATS     = STRINGS.SCRAPBOOK.SUBCATS
local FOODTYPE    = STRINGS.SCRAPBOOK.FOODTYPE
local SPECIALINFO = STRINGS.SCRAPBOOK.SPECIALINFO

SUBCATS.TREASUREBAG = "Treasure Bag"

SPECIALINFO.TREASUREBAG = "A reward for defeating a powerful foe."