local WX78 = STRINGS.CHARACTERS.WX78

WX78.DESCRIBE.OE_MESA_CLAY = "SUBSTRATO MINERAL COMPACTADO"
WX78.DESCRIBE.OE_MESA_ROCK_CLAY = "OBSTRUÇÃO SEDIMENTAR DETECTADA"

WX78.DESCRIBE.OE_MESA_CACTUS_SMALL =
{
    GENERIC = "FLORA ESPINHOSA MENOR DETECTADA",
    PICKED = "SEUS ESPINHOS FORAM REMOVIDOS",
    BURNING = "HA. HA.",
}