local WORMWOOD = STRINGS.CHARACTERS.WORMWOOD

-- Treasure Bags.
WORMWOOD.DESCRIBE.OE_TREASUREBAG = "Gift?"

-- Tools, Weapons, etc.
WORMWOOD.DESCRIBE.OE_FROZEN_TOOL_AXE = "Cold Chopper"
WORMWOOD.DESCRIBE.OE_FROZEN_TOOL_PICKAXE = "Cold!"
WORMWOOD.DESCRIBE.OE_FROZEN_TOOL_SHOVEL = "Brrrr"
WORMWOOD.DESCRIBE.OE_FROZEN_TOOL_HAMMER = "Brrr Tool"
WORMWOOD.DESCRIBE.OE_FROZEN_SWORD = "Cold Sharp Stick"

-- Items.
WORMWOOD.DESCRIBE.OE_TRUE_ICE = "Cold Rock!"