local WORMWOOD = STRINGS.CHARACTERS.WORMWOOD

-- Tools, Weapons, etc.
WORMWOOD.DESCRIBE.OE_FROZEN_TOOL_AXE = "Cold Chopper"
WORMWOOD.DESCRIBE.OE_FROZEN_TOOL_PICKAXE = "Cold!"
WORMWOOD.DESCRIBE.OE_FROZEN_TOOL_SHOVEL = "Brrrr"
WORMWOOD.DESCRIBE.OE_FROZEN_TOOL_HAMMER = "Brrr Tool"
WORMWOOD.DESCRIBE.OE_FROZEN_SWORD = "Cold Sharp Stick"

-- Items.
WORMWOOD.DESCRIBE.OE_TRUE_ICE = "Cold Rock!"

-- Accessories.
WORMWOOD.DESCRIBE.OE_ACCESSORY_BOOTS_MOOSE = "Honk Honk"
WORMWOOD.DESCRIBE.OE_ACCESSORY_BLOOD_CLAW = "Hurts Things"
WORMWOOD.DESCRIBE.OE_ACCESSORY_BURNT_SKULL = "Dead Head"
WORMWOOD.DESCRIBE.OE_ACCESSORY_LUCK_DICE = "Roll!"
WORMWOOD.DESCRIBE.OE_ACCESSORY_LUCK_CLOVER = "Hello Friend!"

-- Treasure Bags.
WORMWOOD.DESCRIBE.OE_TREASUREBAG = "Gift?"