local WX78 = STRINGS.CHARACTERS.WX78

-- Treasure Bags.
WX78.DESCRIBE.OE_TREASUREBAG = "SCANNING FOR VALUABLES"

-- Tools, Weapons, etc.
WX78.DESCRIBE.OE_FROZEN_TOOL_AXE = "LOW TEMPERATURE TOOL DETECTED"
WX78.DESCRIBE.OE_FROZEN_TOOL_PICKAXE = "SUBZERO CONDITIONS"
WX78.DESCRIBE.OE_FROZEN_TOOL_SHOVEL = "DIGGING MODULE: FROZEN STATE"
WX78.DESCRIBE.OE_FROZEN_TOOL_HAMMER = "IMPACT DEVICE: COLD"
WX78.DESCRIBE.OE_FROZEN_SWORD = "WEAPONIZED ICE DETECTED"

-- Items.
WX78.DESCRIBE.OE_TRUE_ICE = "SUPERIOR CRYOGENIC MATERIAL DETECTED"