local WX78 = STRINGS.CHARACTERS.WX78

-- Tools, Weapons, etc.
WX78.DESCRIBE.OE_FROZEN_TOOL_AXE = "LOW TEMPERATURE TOOL DETECTED"
WX78.DESCRIBE.OE_FROZEN_TOOL_PICKAXE = "SUBZERO CONDITIONS"
WX78.DESCRIBE.OE_FROZEN_TOOL_SHOVEL = "DIGGING MODULE: FROZEN STATE"
WX78.DESCRIBE.OE_FROZEN_TOOL_HAMMER = "IMPACT DEVICE: COLD"
WX78.DESCRIBE.OE_FROZEN_SWORD = "WEAPONIZED ICE DETECTED"

-- Items.
WX78.DESCRIBE.OE_TRUE_ICE = "SUPERIOR CRYOGENIC MATERIAL DETECTED"

-- Accessories.
WX78.DESCRIBE.OE_ACCESSORY_BOOTS_MOOSE = "THIS FOOT ARMOR ONLY WORKS WHEN MY ENEMY DOES"
WX78.DESCRIBE.OE_ACCESSORY_BLOOD_CLAW = "CONTAMINATED WITH BIOLOGICAL FLUIDS"
WX78.DESCRIBE.OE_ACCESSORY_BURNT_SKULL = "CARBONIZED ORGANIC PROCESSOR"
WX78.DESCRIBE.OE_ACCESSORY_LUCK_DICE = "RANDOM NUMBER GENERATOR"
WX78.DESCRIBE.OE_ACCESSORY_LUCK_CLOVER = "ILLOGICAL SUPERSTITION TOKEN"

-- Treasure Bags.
WX78.DESCRIBE.OE_TREASUREBAG = "SCANNING FOR VALUABLES"