local WX78 = STRINGS.CHARACTERS.WX78

WX78.DESCRIBE.OE_MESA_CLAY = "COMPRESSED MINERAL SUBSTRATE"
WX78.DESCRIBE.OE_MESA_ROCK_CLAY = "SEDIMENTARY OBSTRUCTION DETECTED"

WX78.DESCRIBE.OE_MESA_CACTUS_SMALL =
{
    GENERIC = "MINOR SPIKED FLORA DETECTED",
    PICKED = "ITS SPIKES HAVE BEEN REMOVED",
    BURNING = "HA. HA.",
}